blueprint:
  name: Xiaomi WXKG02LM_rev2 Zigbee Wireless Switch
  description: Automate your Xiaomi WXKG02LM_rev2 Zigbee Wireless Switch via Zigbee2MQTT.
  domain: automation
  input:
    switch:
      name: Xiaomi WXKG02LM_rev2 Zigbee Wireless Switch
      description: Xiaomi WXKG02LM_rev2 Zigbee Wireless Switch to use
      selector:
        entity:
          integration: mqtt
          domain: sensor
    single_left:
      name: Single Press - Left Button
      description: Action to run on "single_left"
      default: []
      selector:
        action: {}
    double_left:
      name: Double Press - Left Button
      description: Action to run on "double_left"
      default: []
      selector:
        action: {}
    hold_left:
      name: Long Press - Left Button
      description: Action to run on "hold_left"
      default: []
      selector:
        action: {}
    single_right:
      name: Single Press - Right Button
      description: Action to run on "single_right"
      default: []
      selector:
        action: {}
    double_right:
      name: Double Press - Right Button
      description: Action to run on "double_right"
      default: []
      selector:
        action: {}
    hold_right:
      name: Long Press - Right Button
      description: Action to run on "hold_right"
      default: []
      selector:
        action: {}
    single_both:
      name: Single Press - Both Buttons
      description: Action to run on "single_both"
      default: []
      selector:
        action: {}
    double_both:
      name: Double Press - Both Buttons
      description: Action to run on "double_both"
      default: []
      selector:
        action: {}
    hold_both:
      name: Long Press - Both Buttons
      description: Action to run on "hold_both"
      default: []
      selector:
        action: {}
  source_url: https://github.com/jamfrade/homeassistant_files/blob/main/blueprints/aqara_double_switch.yaml
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input "switch"
action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'single_left' }}"
        sequence: !input "single_left"
      - conditions:
          - "{{ command == 'single_right' }}"
        sequence: !input "single_right"
      - conditions:
          - "{{ command == 'single_both' }}"
        sequence: !input "single_both"
      - conditions:
          - "{{ command == 'double_left' }}"
        sequence: !input "double_left"
      - conditions:
          - "{{ command == 'double_right' }}"
        sequence: !input "double_right"
      - conditions:
          - "{{ command == 'double_both' }}"
        sequence: !input "double_both"
      - conditions:
          - "{{ command == 'hold_left' }}"
        sequence: !input "hold_left"
      - conditions:
          - "{{ command == 'hold_right' }}"
        sequence: !input "hold_right"
      - conditions:
          - "{{ command == 'hold_both' }}"
        sequence: !input "hold_both"
