blueprint:
  name: Xiaomi WXKG02LM_rev2 Zigbee Wireless Switch
  description: Automate your Xiaomi WXKG02LM_rev2 Zigbee Wireless Switch via Zigbee2MQTT.
  domain: automation
  input:
    switch:
      name: Xiaomi WXKG02LM_rev2 Zigbee Wireless Switch
      description: Xiaomi WXKG02LM_rev2 Zigbee Wireless Switch to use
      selector:
        entity:
          integration: mqtt
          domain: sensor
    left_button_short_press:
      name: Single Press - Left Button
      description: Action to run on \"single_left\"
      default: []
      selector:
        action: {}
    left_button_double_press:
      name: Double Press - Left Button
      description: Action to run on double_left
      default: []
      selector:
        action: {}
    left_button_long_press:
      name: Long Press - Left Button
      description: Action to run on hold_left
      default: []
      selector:
        action: {}
    right_button_short_press:
      name: Single Press - Right Button
      description: Action to run on single_right
      default: []
      selector:
        action: {}
    right_button_double_press:
      name: Double Press - Right Button
      description: Action to run on double_right
      default: []
      selector:
        action: {}
    right_button_long_press:
      name: Long Press - Right Button
      description: Action to run on hold_right
      default: []
      selector:
        action: {}
    both_buttons_short_press:
      name: Single Press - Both Buttons
      description: Action to run on single_both
      default: []
      selector:
        action: {}
    both_buttons_double_press:
      name: Double Press - Both Buttons
      description: Action to run on double_both
      default: []
      selector:
        action: {}
    both_buttons_long_press:
      name: Long Press - Both Buttons
      description: Action to run on hold_both
      default: []
      selector:
        action: {}
  source_url: https://github.com/jamfrade/homeassistant_files/blob/main/blueprints/aqara_double_switch.yaml
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input "switch"
action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'single_left' }}"
        sequence: !input "left_button_short_press"
      - conditions:
          - "{{ command == 'single_right' }}"
        sequence: !input "right_button_short_press"
      - conditions:
          - "{{ command == 'single_both' }}"
        sequence: !input "both_buttons_short_press"
      - conditions:
          - "{{ command == 'double_left' }}"
        sequence: !input "left_button_double_press"
      - conditions:
          - "{{ command == 'double_right' }}"
        sequence: !input "right_button_double_press"
      - conditions:
          - "{{ command == 'double_both' }}"
        sequence: !input "both_buttons_double_press"
      - conditions:
          - "{{ command == 'hold_left' }}"
        sequence: !input "left_button_long_press"
      - conditions:
          - "{{ command == 'hold_right' }}"
        sequence: !input "right_button_long_press"
      - conditions:
          - "{{ command == 'hold_both' }}"
        sequence: !input "both_buttons_long_press"
